//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.27 at 04:59:29 PM MSD 
//


package nl.leocms.connectors.UISconnector.input.customers.model.impl;

public class CustomerInformationTypeImpl implements nl.leocms.connectors.UISconnector.input.customers.model.CustomerInformationType, com.sun.xml.bind.JAXBObject, nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.UnmarshallableObject, nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.XMLSerializable, nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.ValidatableObject
{

    protected nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType _PropertyList;
    protected nl.leocms.connectors.UISconnector.input.customers.model.AddressType _Address;
    protected nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType _BusinessInformation;
    protected nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType _CommonInformation;
    protected nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType _PersonalInformation;
    public final static java.lang.Class version = (nl.leocms.connectors.UISconnector.input.customers.model.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (nl.leocms.connectors.UISconnector.input.customers.model.CustomerInformationType.class);
    }

    public nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType getPropertyList() {
        return _PropertyList;
    }

    public void setPropertyList(nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType value) {
        _PropertyList = value;
    }

    public nl.leocms.connectors.UISconnector.input.customers.model.AddressType getAddress() {
        return _Address;
    }

    public void setAddress(nl.leocms.connectors.UISconnector.input.customers.model.AddressType value) {
        _Address = value;
    }

    public nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType getBusinessInformation() {
        return _BusinessInformation;
    }

    public void setBusinessInformation(nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType value) {
        _BusinessInformation = value;
    }

    public nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType getCommonInformation() {
        return _CommonInformation;
    }

    public void setCommonInformation(nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType value) {
        _CommonInformation = value;
    }

    public nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType getPersonalInformation() {
        return _PersonalInformation;
    }

    public void setPersonalInformation(nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType value) {
        _PersonalInformation = value;
    }

    public nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.UnmarshallingEventHandler createUnmarshaller(nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.UnmarshallingContext context) {
        return new nl.leocms.connectors.UISconnector.input.customers.model.impl.CustomerInformationTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_PersonalInformation instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _PersonalInformation), "PersonalInformation");
        } else {
            context.startElement("", "personalInformation");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _PersonalInformation), "PersonalInformation");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _PersonalInformation), "PersonalInformation");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _PersonalInformation), "PersonalInformation");
            context.endElement();
        }
        if (_BusinessInformation instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _BusinessInformation), "BusinessInformation");
        } else {
            context.startElement("", "businessInformation");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _BusinessInformation), "BusinessInformation");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _BusinessInformation), "BusinessInformation");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _BusinessInformation), "BusinessInformation");
            context.endElement();
        }
        if (_CommonInformation instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _CommonInformation), "CommonInformation");
        } else {
            context.startElement("", "commonInformation");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CommonInformation), "CommonInformation");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CommonInformation), "CommonInformation");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _CommonInformation), "CommonInformation");
            context.endElement();
        }
        if (_Address instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Address), "Address");
        } else {
            context.startElement("", "address");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Address), "Address");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Address), "Address");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Address), "Address");
            context.endElement();
        }
        if (_PropertyList instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _PropertyList), "PropertyList");
        } else {
            context.startElement("", "propertyList");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _PropertyList), "PropertyList");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _PropertyList), "PropertyList");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _PropertyList), "PropertyList");
            context.endElement();
        }
    }

    public void serializeAttributes(nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_PersonalInformation instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _PersonalInformation), "PersonalInformation");
        }
        if (_BusinessInformation instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _BusinessInformation), "BusinessInformation");
        }
        if (_CommonInformation instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CommonInformation), "CommonInformation");
        }
        if (_Address instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Address), "Address");
        }
        if (_PropertyList instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _PropertyList), "PropertyList");
        }
    }

    public void serializeURIs(nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_PersonalInformation instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _PersonalInformation), "PersonalInformation");
        }
        if (_BusinessInformation instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _BusinessInformation), "BusinessInformation");
        }
        if (_CommonInformation instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CommonInformation), "CommonInformation");
        }
        if (_Address instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Address), "Address");
        }
        if (_PropertyList instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _PropertyList), "PropertyList");
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (nl.leocms.connectors.UISconnector.input.customers.model.CustomerInformationType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000!com.sun.msv.grammar.InterleaveExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom."
+"sun.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/g"
+"rammar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expres"
+"sion\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L"
+"\u0000\u000bexpandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.ms"
+"v.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.gramma"
+"r.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/"
+"grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp"
+"\u0000sq\u0000~\u0000\tppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001c"
+"com.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011"
+"java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.gram"
+"mar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\fxq\u0000~\u0000"
+"\u0003q\u0000~\u0000\u0014psr\u00002com.sun.msv.grammar.Expression$AnyStringExpressio"
+"n\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u0013\u0001psr\u0000 com.sun.msv.grammar.AnyNameCla"
+"ss\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xps"
+"r\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0019psr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000 xq\u0000"
+"~\u0000\u001bt\u0000Knl.leocms.connectors.UISconnector.input.customers.mode"
+"l.PersonalInformationt\u0000+http://java.sun.com/jaxb/xjc/dummy-e"
+"lementssq\u0000~\u0000\u000bpp\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xq\u0000~\u0000\u0001ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000"
+"\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000Onl.leocms.connectors.UISconnector.input.custo"
+"mers.model.PersonalInformationTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014ps"
+"r\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxn"
+"g/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/uti"
+"l/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fname"
+"spaceUriq\u0000~\u0000 L\u0000\btypeNameq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/da"
+"tatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/X"
+"MLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProce"
+"ssor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSp"
+"aceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$"
+"NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.Str"
+"ingPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceURIq\u0000~\u0000 xpq\u0000~"
+"\u0000:q\u0000~\u00009sq\u0000~\u0000\u001ft\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-inst"
+"anceq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0013personalInformationt\u0000\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u000bpp\u0000sq\u0000"
+"~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000Knl.leoc"
+"ms.connectors.UISconnector.input.customers.model.BusinessInf"
+"ormationq\u0000~\u0000#sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000%ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014ps"
+"q\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000Onl.leocms.connectors.UISc"
+"onnector.input.customers.model.BusinessInformationTypeq\u0000~\u0000#s"
+"q\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0013businessInformati"
+"onq\u0000~\u0000Gsq\u0000~\u0000\tppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000"
+"\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000Inl.leocms.connectors.UISconnector.input."
+"customers.model.CommonInformationq\u0000~\u0000#sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000%ppsq\u0000~\u0000"
+"\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000M"
+"nl.leocms.connectors.UISconnector.input.customers.model.Comm"
+"onInformationTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001esq\u0000"
+"~\u0000\u001ft\u0000\u0011commonInformationq\u0000~\u0000Gsq\u0000~\u0000\tppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q"
+"\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000?nl.leocms.connector"
+"s.UISconnector.input.customers.model.Addressq\u0000~\u0000#sq\u0000~\u0000\u000bpp\u0000sq"
+"\u0000~\u0000%ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~"
+"\u0000\u001esq\u0000~\u0000\u001ft\u0000Cnl.leocms.connectors.UISconnector.input.customers"
+".model.AddressTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001esq"
+"\u0000~\u0000\u001ft\u0000\u0007addressq\u0000~\u0000Gsq\u0000~\u0000\tppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~"
+"\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000Dnl.leocms.connectors.UISconn"
+"ector.input.customers.model.PropertyListq\u0000~\u0000#sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000%"
+"ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq"
+"\u0000~\u0000\u001ft\u0000Hnl.leocms.connectors.UISconnector.input.customers.mod"
+"el.PropertyListTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001es"
+"q\u0000~\u0000\u001ft\u0000\fpropertyListq\u0000~\u0000Gsr\u0000\"com.sun.msv.grammar.ExpressionP"
+"ool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionP"
+"ool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Clos"
+"edHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/su"
+"n/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\'\u0001pq\u0000~\u0000\u000fq\u0000~\u0000(q\u0000~\u0000Jq\u0000~\u0000Rq\u0000~"
+"\u0000]q\u0000~\u0000eq\u0000~\u0000pq\u0000~\u0000xq\u0000~\u0000\u0083q\u0000~\u0000\u008bq\u0000~\u0000\u0006q\u0000~\u0000\nq\u0000~\u0000Hq\u0000~\u0000[q\u0000~\u0000nq\u0000~\u0000\u0081q\u0000~"
+"\u0000&q\u0000~\u0000Pq\u0000~\u0000cq\u0000~\u0000vq\u0000~\u0000\u0089q\u0000~\u0000\bq\u0000~\u0000\u0012q\u0000~\u0000)q\u0000~\u0000Kq\u0000~\u0000Sq\u0000~\u0000^q\u0000~\u0000fq\u0000~"
+"\u0000qq\u0000~\u0000yq\u0000~\u0000\u0084q\u0000~\u0000\u008cq\u0000~\u0000\u0005q\u0000~\u0000-q\u0000~\u0000Wq\u0000~\u0000jq\u0000~\u0000}q\u0000~\u0000\u0090q\u0000~\u0000\u0007x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.UnmarshallingContext context) {
            super(context, "-----------");
        }

        protected Unmarshaller(nl.leocms.connectors.UISconnector.input.customers.model.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return nl.leocms.connectors.UISconnector.input.customers.model.impl.CustomerInformationTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  7 :
                        if (("faxNo" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("emailAddress" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("telephoneNo" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("gender" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("birthDate" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("lastName" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("suffix" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("firstName" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("initials" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  1 :
                        if (("property" == ___local)&&("" == ___uri)) {
                            _PropertyList = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PropertyListTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PropertyListTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("property" == ___local)&&("" == ___uri)) {
                            _PropertyList = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PropertyListTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PropertyListTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  9 :
                        if (("contactPersonId" == ___local)&&("" == ___uri)) {
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("isMember" == ___local)&&("" == ___uri)) {
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("customerId" == ___local)&&("" == ___uri)) {
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("giroAccount" == ___local)&&("" == ___uri)) {
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("bankAccount" == ___local)&&("" == ___uri)) {
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  5 :
                        if (("city" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("zipCode" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("extraInfo" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("streetName" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("houseNumberExtension" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("houseNumber" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("addressType" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("countryId" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  3 :
                        if (("emailAddress" == ___local)&&("" == ___uri)) {
                            _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("telephoneNo" == ___local)&&("" == ___uri)) {
                            _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("vatNo" == ___local)&&("" == ___uri)) {
                            _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("companyName" == ___local)&&("" == ___uri)) {
                            _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  0 :
                        if (("propertyList" == ___local)&&("" == ___uri)) {
                            _PropertyList = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PropertyListImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PropertyListImpl.class), 0, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("propertyList" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        if (("address" == ___local)&&("" == ___uri)) {
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressImpl.class), 0, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("address" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 5;
                            return ;
                        }
                        if (("commonInformation" == ___local)&&("" == ___uri)) {
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationImpl.class), 0, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("commonInformation" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 9;
                            return ;
                        }
                        if (("businessInformation" == ___local)&&("" == ___uri)) {
                            _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationImpl.class), 0, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("businessInformation" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 3;
                            return ;
                        }
                        if (("personalInformation" == ___local)&&("" == ___uri)) {
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationImpl) spawnChildFromEnterElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationImpl.class), 0, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("personalInformation" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 7;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  8 :
                        if (("personalInformation" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  7 :
                        _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromLeaveElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname));
                        return ;
                    case  9 :
                        _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromLeaveElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname));
                        return ;
                    case  5 :
                        _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromLeaveElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  6 :
                        if (("address" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  3 :
                        _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromLeaveElement((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname));
                        return ;
                    case  4 :
                        if (("businessInformation" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  10 :
                        if (("commonInformation" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("propertyList" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  0 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  7 :
                        _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromEnterAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname));
                        return ;
                    case  9 :
                        _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromEnterAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname));
                        return ;
                    case  5 :
                        _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromEnterAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromEnterAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  7 :
                        _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromLeaveAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, ___uri, ___local, ___qname));
                        return ;
                    case  9 :
                        _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromLeaveAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, ___uri, ___local, ___qname));
                        return ;
                    case  5 :
                        _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromLeaveAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromLeaveAttribute((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  7 :
                            _PersonalInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl) spawnChildFromText((nl.leocms.connectors.UISconnector.input.customers.model.impl.PersonalInformationTypeImpl.class), 8, value));
                            return ;
                        case  9 :
                            _CommonInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl) spawnChildFromText((nl.leocms.connectors.UISconnector.input.customers.model.impl.CommonInformationTypeImpl.class), 10, value));
                            return ;
                        case  5 :
                            _Address = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl) spawnChildFromText((nl.leocms.connectors.UISconnector.input.customers.model.impl.AddressTypeImpl.class), 6, value));
                            return ;
                        case  3 :
                            _BusinessInformation = ((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl) spawnChildFromText((nl.leocms.connectors.UISconnector.input.customers.model.impl.BusinessInformationTypeImpl.class), 4, value));
                            return ;
                        case  0 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
