<%@page import="java.io.*,org.mmbase.bridge.*" %>
<%@page language="java" contentType="text/html;charset=UTF-8"%>
<%@taglib uri="http://www.mmbase.org/mmbase-taglib-1.0" prefix="mm"%>
<mm:cloud method="http" rank="basic user" jspvar="cloud">
<html>
   <head>
   <LINK rel="stylesheet" type="text/css" href="/editors/css/editorstyle.css">
   <title>Natuurmonumenten</title>
   <style>
     table { width: 100%; }
     td { border: solid #000000 1px; padding: 3px; height: auto; vertical-align: top; } 
   </style>
   </head>
   <body style="width:100%;padding:5px;">
   Changes made in this update:<br/>
   1. Creating the missing afdeling to natuurgebied relations.<br/>
   
<%
String createdRelations = "";
String alreadyExistingRelations = "";
String couldntCreateRelations = "";

for (int i1 =0; i1 < data.length; i1++) {
	String [] innerArray = data[i1];
	String afdeling = innerArray[0].trim();
	String gebied = innerArray[1].trim();
	String gebiedconstraint = "natuurgebieden.titel=='" + org.mmbase.util.Encode.encode("ESCAPE_SINGLE_QUOTE",gebied) + "'";
	String afdelingconstraint = "afdelingen.titel==\"" + org.mmbase.util.Encode.encode("ESCAPE_SINGLE_QUOTE",afdeling) + "\"";
	boolean hasRelated = false; 
	boolean created = false;
%>

<mm:listnodes type="natuurgebieden" constraints="<%=gebiedconstraint%>" max="1" id="this_gebied">
	<mm:related path="posrel,afdelingen" constraints="<%=afdelingconstraint%>">
		<% hasRelated = true; %> 
	</mm:related>	

	<% if (!hasRelated) {
	//if false set relation here
	%>
		<mm:listnodes type="afdelingen" constraints="<%=afdelingconstraint%>" max="1" id="this_afdeling">
				<mm:field name="titel">
				<mm:isnotempty>
					<mm:createrelation source="this_gebied" destination="this_afdeling" role="posrel" />
					<% createdRelations += "from: " + gebied + " to: " + afdeling + "<br/>"; %>
					<% created = true; %>
				</mm:isnotempty>
				</mm:field>
		</mm:listnodes> 
		<mm:remove referid="this_afdeling" />
		<% if (!created) {
			couldntCreateRelations += "from: " + gebied + " to: " + afdeling + "<br/>";
		} %>
	<% } else {
		alreadyExistingRelations += "from: " + gebied + " to: " + afdeling + "<br/>";
	} %>

</mm:listnodes> 
<mm:remove referid="this_gebied" />
<%
// for loop
}
%>
   Processing...<br/>
   Done.<p/>

   
   <b>Couldn't Create:</b><br/>
   <%=couldntCreateRelations%>
   <br/>
   <b>Created:</b><br/>
   <%=createdRelations%>
   <br/>
   <b>Not Created:</b><br/>
   <%=alreadyExistingRelations%>
  
  </html>
</mm:cloud>

<%!
 String[][] data = {
      { "	Groningen en N-Drenthe	", "	Noordlaarderbos	" },
      { "	Groningen en N-Drenthe	", "	Vijftig Bunder	" },
      { "	Groningen en N-Drenthe	", "	Braak	" },
      { "	Groningen en N-Drenthe	", "	Friese Veen	" },
      { "	Groningen en N-Drenthe	", "	Polder het Oosterland	" },
      { "	Groningen en N-Drenthe	", "	Hoge Land	" },
      { "	Groningen en N-Drenthe	", "	Elsburger Onland	" },
      { "	Groningen en N-Drenthe	", "	Westerbroek	" },
      { "	Waddengebied	", "	Dollard	" },
      { "	Waddengebied	", "	Nationaal Park Schiermonnikoog	" },
      { "	Waddengebied	", "	Nationaal Park Lauwersmeer	" },
      { "	Waddengebied	", "	Griend	" },
      { "	Noordenveld	", "	Haulerpolder	" },
      { "	Groningen en N-Drenthe	", "	Ruiten A	" },
      { "	Noordenveld	", "	Norger Esdorpenlandschap	" },
      { "	Zuidwest-Friesland	", "	Oudemirdumerklif	" },
      { "	Zuidwest-Friesland	", "	Skrok	" },
      { "	Zuidwest-Friesland	", "	Filenspolder	" },
      { "	Zuidwest-Friesland	", "	Zuiderfennenspolder	" },
      { "	Zuidwest-Friesland	", "	Lycklamabos	" },
      { "	Zuidwest-Friesland	", "	Flietsterbosk	" },
      { "	Zuidwest-Friesland	", "	Lionserpolder	" },
      { "	Zuidwest-Friesland	", "	Westerhitzumerbos	" },
      { "	Zuid-Drenthe	", "	Nationaal Park Drents-Friese Wold	" },
      { "	Zuid-Drenthe	", "	Nationaal Park Dwingelderveld	" },
      { "	Zuid-Drenthe	", "	Broekenlaar	" },
      { "	Zuid-Drenthe	", "	Berghuizen	" },
      { "	Zuid-Drenthe	", "	Klencke	" },
      { "	Zuid-Drenthe	", "	Baarwelsleek	" },
      { "	Zuid-Drenthe	", "	Exloo *	" },
      { "	Zuid-Drenthe	", "	Hiemstrastate	" },
      { "	Zuid-Drenthe	", "	Mantingerbos en -weiden	" },
      { "	Zuid-Drenthe	", "	Mantingerveld	" },
      { "	De Wieden c.a.	", "	Wieden	" },
      { "	De Wieden c.a.	", "	Hoge Land van Vollenhove	" },
      { "	Voorsterbos c.a.	", "	Vreugderijkerwaard	" },
      { "	Salland	", "	Belten *	" },
      { "	Harderhoek	", "	Harderbos	" },
      { "	Harderhoek	", "	Kievitslanden	" },
      { "	Salland	", "	Rechterense Veld	" },
      { "	Salland	", "	Nationaal Park Sallandse Heuvelrug	" },
      { "	Salland	", "	Alerdinck	" },
      { "	Salland	", "	Hoge Broek	" },
      { "	Noordoost-Twente	", "	Hazelbekke	" },
      { "	Noordoost-Twente	", "	Hakenberg	" },
      { "	Noordoost-Twente	", "	Elfterheurne	" },
      { "	Noordoost-Twente	", "	Boerskotten	" },
      { "	Noordoost-Twente	", "	Snippert	" },
      { "	Noordoost-Twente	", "	Haagse Bos	" },
      { "	Noordoost-Twente	", "	Meyling *	" },
      { "	Zuid-Twente	", "	Stepelerveld	" },
      { "	Zuid-Twente	", "	Witte Veen	" },
      { "	Noordwest-Veluwe	", "	Oud Groevenbeek	" },
      { "	Noordwest-Veluwe	", "	Zwarte Broek	" },
      { "	Veluwezoom	", "	Nationaal Park Veluwezoom	" },
      { "	Veluwezoom	", "	Vaalwaard	" },
      { "	Veluwezoom	", "	Velperwaarden	" },
      { "	Winterswijk	", "	Vragenderveld	" },
      { "	Winterswijk	", "	Korenburgerveen	" },
      { "	Winterswijk	", "	Bönnink	" },
      { "	Winterswijk	", "	Stortelersbeek	" },
      { "	Winterswijk	", "	Beurzerbeek	" },
      { "	Winterswijk	", "	Buskersbos	" },
      { "	Winterswijk	", "	Bekendelle	" },
      { "	Winterswijk	", "	Wooldse Veen	" },
      { "	De Graafschap	", "	Hassinkbos	" },
      { "	De Graafschap	", "	Dorth	" },
      { "	De Graafschap	", "	Larense Broek	" },
      { "	De Graafschap	", "	Waliën	" },
      { "	De Graafschap	", "	Enzerinck	" },
      { "	Montferland	", "	Bijvanck	" },
      { "	Zuidwest-Veluwe	", "	Planken Wambuis	" },
      { "	Oost-Veluwe	", "	Appense Veld	" },
      { "	Oost-Veluwe	", "	Voorstonden	" },
      { "	Oost-Veluwe	", "	Beekbergerwoud	" },
      { "	Zuidwest-Veluwe	", "	Deelerwoud	" },
      { "	Oost-Veluwe	", "	Empese en Tondense Heide	" },
      { "	Oost-Veluwe	", "	Munsterman	" },
      { "	Oost-Veluwe	", "	Reeënberg	" },
      { "	Naardermeer	", "	Naardermeer	" },
      { "	Naardermeer	", "	Laegieskamp	" },
      { "	Vechtplassen	", "	Kortenhoefse Plassen	" },
      { "	Vechtplassen	", "	Spiegelplas	" },
      { "	's-Gravelandse Buitenpl.	", "	Schoonoord	" },
      { "	's-Gravelandse Buitenpl.	", "	Cronebos	" },
      { "	's-Gravelandse Buitenpl.	", "	Corversbos	" },
      { "	's-Gravelandse Buitenpl.	", "	Spanderswoud	" },
      { "	Noord-Holland Noord	", "	Schorren	" },
      { "	Noord-Holland Noord	", "	Lage Land van Texel	" },
      { "	Kennemerland	", "	Nijenburg	" },
      { "	Kennemerland	", "	Loterijlanden	" },
      { "	Wormer- en Jisperveld ca	", "	Fort aan de Middenweg	" },
      { "	Wormer- en Jisperveld ca	", "	Fort bij Spijkerboor	" },
      { "	Noord-Holland Noord	", "	Zwanenwater	" },
      { "	Kennemerland	", "	Nationaal Park Zuid-Kennemerland	" },
      { "	Wormer- en Jisperveld ca	", "	Wormer- en Jisperveld	" },
      { "	Wormer- en Jisperveld ca	", "	IJdoorn	" },
      { "	Vechtplassen	", "	Loosdrechtse Plassen	" },
      { "	Vechtplassen	", "	Wijde Blik	" },
      { "	's-Gravelandse Buitenpl.	", "	Land en Bosch	" },
      { "	Vechtplassen	", "	Fort Nieuwersluis	" },
      { "	Vechtplassen	", "	Hol	" },
      { "	Utrecht	", "	Soesterveen	" },
      { "	Utrecht	", "	Op Hees	" },
      { "	Vechtplassen	", "	Botshol	" },
      { "	Vechtplassen	", "	Fort Nigtevecht	" },
      { "	Vechtplassen	", "	Polder Groot-Mijdrecht	" },
      { "	's-Gravelandse Buitenpl.	", "	Einde Gooi	" },
      { "	Vechtplassen	", "	Tienhovense Plassen	" },
      { "	Utrecht	", "	Nationaal Park Utrechtse Heuvelrug	" },
      { "	Utrecht	", "	Eemland	" },
      { "	Utrecht	", "	Stoutenburg	" },
      { "	Utrecht	", "	Coelhorst	" },
      { "	Nieuwkoop/Delfland	", "	Nieuwkoopse Plassen	" },
      { "	Nieuwkoop/Delfland	", "	Bovenlanden Kromme Mijdrecht	" },
      { "	Nieuwkoop/Delfland	", "	Kadelanden	" },
      { "	Nieuwkoop/Delfland	", "	Vlietlanden	" },
      { "	Nieuwkoop/Delfland	", "	Eendenkooi Schipluiden	" },
      { "	Nieuwkoop/Delfland	", "	Aalkeetbuitenpolder	" },
      { "	Deltakust	", "	Voornes Duin	" },
      { "	Deltakust	", "	Quackgors	" },
      { "	Deltakust	", "	Meertje de Waal	" },
      { "	Deltakust	", "	Duinen van Goeree	" },
      { "	Deltakust	", "	Scheelhoek	" },
      { "	Haringvliet/Krammer Volk.	", "	Korendijkse Slikken	" },
      { "	Tiengemeten	", "	Tiengemeten	" },
      { "	Schelde	", "	Middelplaten	" },
      { "	Schelde	", "	Kwistenburg	" },
      { "	Schelde	", "	Katse Plaat	" },
      { "	Schelde	", "	Schenge	" },
      { "	Schelde	", "	Biezelingse Ham	" },
      { "	Schelde	", "	Zwaakse Weel	" },
      { "	Schelde	", "	Inlaag 1887	" },
      { "	Haringvliet/Krammer Volk.	", "	Steenbergse Vliet	" },
      { "	Haringvliet/Krammer Volk.	", "	West-Brabantse Dijken	" },
      { "	Schelde	", "	Neeltje Jans	" },
      { "	Schelde	", "	Sluis *	" },
      { "	Schelde	", "	Platen van Hulst	" },
      { "	West-Brabant	", "	Lange Maten	" },
      { "	West-Brabant	", "	Oude Buisse Heide	" },
      { "	West-Brabant	", "	Moeren	" },
      { "	West-Brabant	", "	Markdal	" },
      { "	West-Brabant	", "	Rucphense Bossen	" },
      { "	West-Brabant	", "	Oosterheide	" },
      { "	West-Brabant	", "	Chaamse Beek	" },
      { "	Noordoost-Brabant & Mook	", "	Elshoutse Wielen	" },
      { "	Kempen & Midden-Limburg	", "	Maaij	" },
      { "	Kempen & Midden-Limburg	", "	Mirandolles Heike	" },
      { "	Midden-Brabant	", "	Kampina	" },
      { "	Noordoost-Brabant & Mook	", "	Molentje	" },
      { "	Stippelberg	", "	Stippelberg	" },
      { "	Noordoost-Brabant & Mook	", "	Rivierduintjes	" },
      { "	Noordoost-Brabant & Mook	", "	Sint-Jansberg	" },
      { "	Kempen & Midden-Limburg	", "	Hout	" },
      { "	Kempen & Midden-Limburg	", "	Heioord	" },
      { "	Kempen & Midden-Limburg	", "	Keversbroek	" },
      { "	Kempen & Midden-Limburg	", "	Uffelse Beek	" },
      { "	Kempen & Midden-Limburg	", "	Koningslust *	" },
      { "	Kempen & Midden-Limburg	", "	Grensmaas	" },
      { "	Kempen & Midden-Limburg	", "	Grasbroek	" },
      { "	Kempen & Midden-Limburg	", "	Krang	" },
      { "	Kempen & Midden-Limburg	", "	Areven	" },
      { "	Zuid-Limburg	", "	Spaubekerbos	" },
      { "	Zuid-Limburg	", "	Sint-Pietersberg	" },
      { "	Zuid-Limburg	", "	Kelmonderbos	" },
      { "	Zuid-Limburg	", "	Mechelderbeekdal	" },
      { "	Zuid-Limburg	", "	Bovenste Bos	" },
      { "	Zuid-Limburg	", "	Genhoes	" },
      { "	Zuid-Limburg	", "	Imstenraderbos	" },
      { "	Zuid-Limburg	", "	Rode Beek	" },
      { "	Zuid-Limburg	", "	Strijthagerbeekdal	" },
      { "	Zuid-Limburg	", "	Wormdal	" },
      { "	Zuid-Limburg	", "	Terworm	" },
      { "	Midden-Brabant	", "	Huis ter Heide	" },
      { "	Midden-Brabant	", "	Nationaal Park Loonse en Drunense Duinen	" },
      { "	Midden-Brabant	", "	Zwijnsbergen	" },
      { "	Salland	", "	Eerde	" },
      { "	Salland	", "	Colckhof	" },
      { "	Noordoost-Twente	", "	Roderveld	" },
      { "	Noordoost-Twente	", "	Duivelshof	" },
      { "	Noordoost-Twente	", "	Tip	" },
      { "	Zuid-Twente	", "	Buurserzand	" },
      { "	Noordwest-Veluwe	", "	Veluwemeerkust	" },
      { "	Noordwest-Veluwe	", "	Vicary van Nijkerk *	" },
      { "	Winterswijk	", "	Borkense Baan	" },
      { "	Winterswijk	", "	Kotten	" },
      { "	Winterswijk	", "	Loohuis	" },
      { "	De Graafschap	", "	Gorsselse Heide	" },
      { "	De Graafschap	", "	Velhorst	" },
      { "	De Graafschap	", "	Hekenbroek	" },
      { "	Montferland	", "	Bergherbos	" },
      { "	Vechtplassen	", "	Ankeveense Plassen	" },
      { "	's-Gravelandse Buitenpl.	", "	Schaep en Burgh	" },
      { "	Deltakust	", "	Kop van Goeree	" },
      { "	Noordwest-Veluwe	", "	Leuvenumse Bossen	" },
      { "	Nieuwkoop/Delfland	", "	Kersbergse en Achthovense Waarden *	" },
      { "	Haringvliet/Krammer Volk.	", "	Groot Koninkrijk	" },
      { "	Schelde	", "	Bloemdijken van Zuid-Beveland	" },
      { "	Deltakust	", "	Slot Haamstede	" },
      { "	Haringvliet/Krammer Volk.	", "	Dintelse Gorzen	" },
      { "	West-Brabant	", "	Vluchtheuvel	" },
      { "	West-Brabant	", "	Wallsteijn	" },
      { "	West-Brabant	", "	Reten	" },
      { "	Noordoost-Brabant & Mook	", "	Gansooiense Uiterwaard	" },
      { "	Noordoost-Brabant & Mook	", "	Maasuiterwaarden	" },
      { "	Kempen & Midden-Limburg	", "	Dommeldal	" },
      { "	Kempen & Midden-Limburg	", "	Plateaux	" },
      { "	Midden-Brabant	", "	Oisterwijkse Bossen en Vennen	" },
      { "	Noordoost-Brabant & Mook	", "	Zevenbergen	" },
      { "	Kempen & Midden-Limburg	", "	Wijffelterbroek	" },
      { "	Kempen & Midden-Limburg	", "	Tungelerwallen	" },
      { "	Kempen & Midden-Limburg	", "	IJzerenbos	" },
      { "	Kempen & Midden-Limburg	", "	Limbrichterbos	" },
      { "	Zuid-Limburg	", "	Geleenbeekdal	" },
      { "	Zuid-Limburg	", "	Vrouwenbos	" },
      { "	Zuid-Limburg	", "	Groeve Sweijer	" },
      { "	Zuid-Limburg	", "	Berghofweide	" },
      { "	Zuid-Limburg	", "	Selzerbeekdal	" },
      { "	Zuidwest-Veluwe	", "	Hengstdal	" },
      { "	Zuidwest-Veluwe	", "	Wolfheze	" },
      { "	Oost-Veluwe	", "	Loenense Hooilanden	" },
      { "	Oost-Veluwe	", "	Leusveld	" },
      { "	Oost-Veluwe	", "	Hoeve Delle	" },
      { "	Oost-Veluwe	", "	Steilhul	" },
      { "	Schelde	", "	Fort Ellewoutsdijk	" },
      { "	Noordoost-Twente	", "	Galgenven	" },
      { "	Schelde	", "	Zuidkust van Schouwen	" },
      { "	De Graafschap	", "	Esveldsbos	" },
      { "	Groningen en N-Drenthe	", "	Duinen	" },
      { "	West-Brabant	", "	Noordpolder van Ossendrecht	" },
      { "	Nieuwkoop/Delfland	", "	Polder Noord-Kethel	" },
      { "	Waddengebied	", "	Uithuizerwad	" },
      { "	Vechtplassen	", "	Horstermeerpolder	" },
      { "	's-Gravelandse Buitenpl.	", "	Boekesteyn	" },
      { "	Wormer- en Jisperveld ca	", "	Fort aan de Jisperweg	" },
      { "	Vechtplassen	", "	Fort Kijkuit	" },
      { "	Vechtplassen	", "	Uitermeer	" },
      { "	Kennemerland	", "	Weidse Polders	" },
      { "	Utrecht	", "	Birkt	" },
      { "	Noordwest-Veluwe	", "	Emst *	" },
      { "	Zuid-Limburg	", "	Brunssummerheide	" },
      { "	Noordoost-Twente	", "	Beneden-Dinkeldal	" },
      { "	Noordoost-Brabant & Mook	", "	Vlijmens Ven	" },
      { "	Voorsterbos c.a.	", "	Voorsterbos	" },
      { "	Voorsterbos c.a.	", "	Zwarte Meer	" },
      { "	Harderhoek	", "	Harderbroek	" },
      { "	Kempen & Midden-Limburg	", "	Laurabossen	" },
      { "	Zuid-Limburg	", "	Eyserheide	" },
      { "	Noordoost-Twente	", "	IJsbaan Losser	" },
      { "	Vechtplassen	", "	Hinderdam	" },
      { "	Zuid-Limburg	", "	Noordal	" },
      { "	Zuid-Limburg	", "	Geuldal	" },
      { "	Zuidwest-Friesland	", "	Skrins	" },
      { "	Zuidwest-Friesland	", "	Rengersmiede	" },
      { "	Noordenveld	", "	Fochteloërveen	" },
      { "	Groningen en N-Drenthe	", "	Polder Lappenvoort	" },
      { "	Groningen en N-Drenthe	", "	Kluivingsbos	" },
      { "	Zuid-Drenthe	", "	Westerbork *	" },
      { "	Zuid-Drenthe	", "	Leggelderveld	" },
      { "	Zuid-Drenthe	", "	Holtingerveld	" },
      { "	Salland	", "	Raalterwoold	" },
      { "	Noordoost-Twente	", "	Egheria	" },
      { "	Noordoost-Twente	", "	Grevenmaat	" },
      { "	Winterswijk	", "	Mentink	" },
      { "	Winterswijk	", "	Dottinkrade	" },
      { "	's-Gravelandse Buitenpl.	", "	Hilverbeek	" },
      { "	's-Gravelandse Buitenpl.	", "	Gooilust	" },
      { "	Vechtplassen	", "	Nes	" },
      { "	Kennemerland	", "	Harger- en Pettemerpolder	" },
      { "	Noord-Holland Noord	", "	Hoge Berg	" },
      { "	De Graafschap	", "	Grote Veld	" },
      { "	Oost-Veluwe	", "	Soerense Broek	" },
      { "	Oost-Veluwe	", "	Ramenberg	" },
      { "	Utrecht	", "	Grote Maat	" },
      { "	Noordwest-Veluwe	", "	Oldenaller	" },
      { "	Noordoost-Brabant & Mook	", "	Mookerheide	" },
      { "	Kempen & Midden-Limburg	", "	Weerterheide	" },
      { "	Kempen & Midden-Limburg	", "	Stramprooierheide	" },
      { "	Zuid-Limburg	", "	Schinveldse Bossen	" },
      { "	Zuid-Limburg	", "	Horstergrub	" },
      { "	Noordoost-Brabant & Mook	", "	Baardwijkse Overlaat	" },
      { "	Nieuwkoop/Delfland	", "	Kamerikse Nessen	" },
      { "	Deltakust	", "	Merrevliet	" },
      { "	Haringvliet/Krammer Volk.	", "	Beningerslikken	" },
      { "	Schelde	", "	Zuidgors	" },
      { "	Haringvliet/Krammer Volk.	", "	Slikken van de Heen	" },
      { "	Kempen & Midden-Limburg	", "	Cartierheide	" },
      { "	Midden-Brabant	", "	Moergestelse Broek	" },
      { "	's-Gravelandse Buitenpl.	", "	Bantam	" },
      { "	Schelde	", "	Verdronken Land van Zuid-Beveland	" },
      { "	Voorsterbos c.a.	", "	Vogeleiland	" },
      { "	Zuidwest-Friesland	", "	Hegewiersterfjild	" },
      { "	Noordenveld	", "	Slotplaats	" },
      { "	Kempen & Midden-Limburg	", "	Kettingdijk	" },
      { "	Waddengebied	", "	Dokkum *	" },
      { "	Groningen en N-Drenthe	", "	Vennebroek	" },
      { "	Noordoost-Twente	", "	Hoge Venterink	" },
      { "	Groningen en N-Drenthe	", "	Peizermaden	" },
      { "	Kempen & Midden-Limburg	", "	Kruispeel	" },
      { "	Noordoost-Brabant & Mook	", "	Rijskampen	" },
      { "	Schelde	", "	Poel	" },
      { "	's-Gravelandse Buitenpl.	", "	Spiegelrust	" },
      { "	Kempen & Midden-Limburg	", "	Malpiebeemden	" },
      { "	De Graafschap	", "	Beekvliet	" },
      { "	Montferland	", "	Bevermeer	" },
      { "	Noordenveld	", "	Beetsterzwaag	" },
      { "	Kempen & Midden-Limburg	", "	Stevensbergen	" },
      { "	Zuid-Limburg	", "	Wolfshuis	" },
      { "	West-Brabant	", "	Groote Meer	" },
      { "	Salland	", "	Lierderbroek	" },
      { "	Noordoost-Brabant & Mook	", "	Molenheide	" },
      { "	Haringvliet/Krammer Volk.	", "	Slikken bij de Sabina-Henricapolder	" },
      { "	Utrecht	", "	Haarzuilens	" },
      { "	Noordoost-Twente	", "	Molterheurne	" },
      { "	De Graafschap	", "	Hackfort	" },
      { "	Noordoost-Brabant & Mook	", "	Langenboomse Bossen	" },
      { "	Deltakust	", "	Volgerland	" },
      { "	Kempen & Midden-Limburg	", "	Ellburg	" },
      { "	Groningen en N-Drenthe	", "	Hoeksmeer	" },
      { "	Winterswijk	", "	Steenkamp	" },
      { "	Kempen & Midden-Limburg	", "	Vossenbussel	" },
      { "	Vechtplassen	", "	Fort Waver Amstel	" },
      { "	Haringvliet/Krammer Volk.	", "	Tiendgorzen	" },
      { "	Nieuwkoop/Delfland	", "	Ackerdijkse Plassen	" },
      { "	Salland	", "	Velderberg	" },
      { "	Groningen en N-Drenthe	", "	Kardinge	" },
      { "	Deltakust	", "	Annabos	" },
      { "	Winterswijk	", "	Grote Goor	" },
      { "	Utrecht	", "	Kasteel de Haar	" },
      { "	Vechtplassen	", "	Fort bij Abcoude	" },
      { "	's-Gravelandse Buitenpl.	", "	Jagtlust	" },
      { "	Zuid-Limburg	", "	Hof van Limburg	" },
      { "	Nieuwkoop/Delfland	", "	Polder Schieveen	" },
      { "	Noordoost-Twente	", "	Everloo	" },
      { "	Zuidwest-Friesland	", "	Rijsterpolder	" },
      { "	Kempen & Midden-Limburg	", "	Terrein bij Budel (voorlopige naam)	" },
      { "	Oost-Veluwe	", "	Hallse Hooilanden	" },
      { "	Oost-Veluwe	", "	Hiemberg	" },
      { "	Oost-Veluwe	", "	Groot Soerel	" },
      { "	Oost-Veluwe	", "	Loenense Enk	" },
      { "	Schelde	", "	Sloe	" },
      { "	Noordoost-Brabant & Mook	", "	Banen	" },
      { "	Noordoost-Brabant & Mook	", "	Koningsven	" },
      { "	Kempen & Midden-Limburg	", "	Itterbeek	" },
      { "	Groningen en N-Drenthe	", "	Piccardthofplas	" },
      { "	Noordoost-Twente	", "	Beerninkholt	" },
      { "	Groningen en N-Drenthe	", "	Tinallinge	" }
    };
%>