//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.27 at 04:59:29 PM MSD 
//


package nl.leocms.connectors.UISconnector.input.customers.model;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/JAVA/WSDP/16/jaxb/bin/Untitled3.xsd line 47)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}personalInformation"/>
 *         &lt;element ref="{}businessInformation"/>
 *         &lt;element ref="{}commonInformation"/>
 *         &lt;element ref="{}address"/>
 *         &lt;element ref="{}propertyList"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CustomerInformationType {


    /**
     * Gets the value of the propertyList property.
     * 
     * @return
     *     possible object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PropertyList}
     */
    nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType getPropertyList();

    /**
     * Sets the value of the propertyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PropertyList}
     */
    void setPropertyList(nl.leocms.connectors.UISconnector.input.customers.model.PropertyListType value);

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.Address}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.AddressType}
     */
    nl.leocms.connectors.UISconnector.input.customers.model.AddressType getAddress();

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.Address}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.AddressType}
     */
    void setAddress(nl.leocms.connectors.UISconnector.input.customers.model.AddressType value);

    /**
     * Gets the value of the businessInformation property.
     * 
     * @return
     *     possible object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformation}
     */
    nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType getBusinessInformation();

    /**
     * Sets the value of the businessInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformation}
     */
    void setBusinessInformation(nl.leocms.connectors.UISconnector.input.customers.model.BusinessInformationType value);

    /**
     * Gets the value of the commonInformation property.
     * 
     * @return
     *     possible object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.CommonInformation}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType}
     */
    nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType getCommonInformation();

    /**
     * Sets the value of the commonInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.CommonInformation}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType}
     */
    void setCommonInformation(nl.leocms.connectors.UISconnector.input.customers.model.CommonInformationType value);

    /**
     * Gets the value of the personalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformation}
     */
    nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType getPersonalInformation();

    /**
     * Sets the value of the personalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType}
     *     {@link nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformation}
     */
    void setPersonalInformation(nl.leocms.connectors.UISconnector.input.customers.model.PersonalInformationType value);

}
