<mm:import id="area">Gebied</mm:import>
<mm:import id="areas">Gebieden</mm:import>
<mm:import id="numberofareas">Aantal gebieden</mm:import>
<mm:import id="topic">Onderwerp</mm:import>
<mm:import id="topics">Onderwerpen</mm:import>
<mm:import id="numberoftopics">Aantal onderwerpen</mm:import>
<mm:import id="messages">Berichten</mm:import>
<mm:import id="numberofmessages">Aantal berichten</mm:import>
<mm:import id="lastmessage">Laatste bericht</mm:import>
<mm:import id="poster">Geplaatst door</mm:import>
<mm:import id="members">Leden</mm:import>
<mm:import id="numberofmembers">Aantal leden</mm:import>
<mm:import id="numberofviews">Aantal keer bekeken</mm:import>
<mm:import id="numberofnew">Aantal nieuwe leden</mm:import>
<mm:import id="new">Nieuw</mm:import>
<mm:import id="cancel">Annuleren</mm:import>
<mm:import id="commit">Opslaan</mm:import>
<mm:import id="delete">Verwijderen</mm:import>
<mm:import id="webmastermail"><%= nl.leocms.applications.NatMMConfig.getFromEmailAddress() %></mm:import>
<mm:import id="numberonline">Aantal mensen online</mm:import>
<mm:import id="numberofposts">Aantal bijdrages</mm:import>
<% String timeFormat = "d MMMM yyyy, HH:mm"; %>
